package org.uengine.Chap10.Error_Handling_with_Exceptions.Performing_cleanup_with_finally;

public class ThreeException extends Exception {

}
